import Head from "next/head";
import Image from "next/image";
import Nav from "./components/navbar";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Slide from "./components/slide";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WS - interiores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ws_tab2.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin=""
        />
      </Head>

      <main className={styles.main}>
        <Nav />

        <div className={styles.Banner} id="inicio">
          <Image
            src="/banner2.jpeg"
            layout="responsive"
            width={700}
            height={650}
          />
        </div>
        <div className={styles.hero_text}>
          <h1>WS Design de Interiores/</h1>
          <p>
            Empresa especializada: Rebaixamento em dryawll, Fabricação e
            instalação de placas de gesso 3d, Elétrica e iluminação em geral
          </p>
          <Link href="https://l.instagram.com/?u=https%3A%2F%2Fwa.me%2Fmessage%2FFQE6ED7A2JBHM1&e=ATPm5cybSR8j9CihWRjJoF4W17VzeK1mRh7jQKUyPZ_MxNbWd9Oj-a8euijCEKBkIHN8fAaencyHWwObZLz2-Q&s=1">
            <a>Orçamento via Whatsapp</a>
          </Link>
        </div>
        <div className={styles.sobre} id="Sobre">
          <div className={styles.sobre_column}>
            <div className={styles.sobre_column_min}>
              <p>Somos WS desing empresa especializada</p>
              <p>
                <strong> Pensamos em Tudo!</strong>
              </p>
              <p>
                <strong>
                  Desenvolvemos ambientes residenciais e comerciais,
                </strong>{" "}
                desde o layout do espaço até a escolha de cortinas, quadros,
                eletrônicos, iluminação, elétrica, vidros, revestimentos,
                pinturas e muito mais.
              </p>
            </div>
          </div>
          <div className={styles.sobre_column}>
            <div className={styles.SociaisA}>
              <div className={styles.Soci}>
                <li>
                  <Link href="https://www.instagram.com/ws_design_de_interiores/">
                    <a>
                      <img src="/instagram_ready.png"></img>Instagram
                    </a>
                  </Link>
                </li>
                <li>
                  <Link href="https://www.instagram.com/ws_design_de_interiores/">
                    <a>
                      <img src="/facebook_logo.png"></img>Facebook
                    </a>
                  </Link>
                </li>
                <li>
                  <Link href="https://l.instagram.com/?u=https%3A%2F%2Fwa.me%2Fmessage%2FFQE6ED7A2JBHM1&e=ATPRvIHWvq5loUY0TPDGgEQyNnoPnM3lBN9ZPLX-Yv2kepO0oVqlH0Va5by-vUCZFAzqWJoJvcX2j5xti87TOQ&s=1">
                    <a>
                      <img src="/whattsapp_logo.png"></img>Whatsapp
                    </a>
                  </Link>
                </li>
              </div>
            </div>
          </div>
        </div>
        <div id="Galeria">
          <Slide />
        </div>
        <footer className={styles.footer}>
          <p> WS Desing - Todos os Direitos reservados @2022</p>
          <p>
            {" "}
            Atendemos as seguintes regiões - Rio de Janeiro, São Paulo, Minas
            Gerais, Santa Catarina e estados adjacentes ao Rio de Janeiro
          </p>
        </footer>
      </main>
    </div>
  );
}
